version: '3.9'

services:
  db:
    image: mongo:5.0
    ports:
      - 27018:27017
    restart: unless-stopped   
    volumes:
      - appdata:/data/db

# For persistance    
volumes:
  appdata: